#!/usr/bin/env python3
"""
Sample a larger content/style pair set for the quantitative tables.

    python scripts/make_pairs.py --contents 6 --styles 5 --out compare/pairs_large.txt

The eight typical cases in `compare/pairs.txt` were chosen to be shown, not to be
counted. Eight pairs give eight independent units per head-to-head comparison,
which detects only very large effects: the plan-transfer comparison came back
4--2 with two ties (p = 0.69), which is not evidence of anything either way. The
five-method table reaches significance only because it pools four opponents
across the same eight pairs. Any comparison with a single opponent needs more
pairs, and repetitions do not substitute for them -- re-judging the same image
twice adds no independent information about the method.

The sample is a content x style grid rather than random pairs, so that every
style is seen on every content and a style-specific effect cannot be confounded
with which contents happened to be drawn for it. Selection is deterministic given
--seed. Pairs that already have a plan are listed first and marked, since those
can be replayed without re-running the agent.
"""
import argparse
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

EXTS = (".jpg", ".jpeg", ".png")


def stems(d: Path):
    return sorted((p for p in d.iterdir() if p.suffix.lower() in EXTS),
                  key=lambda p: (len(p.stem), p.stem))


def existing_plans(runs_root: Path):
    out = set()
    if not runs_root.exists():
        return out
    for plan in runs_root.rglob("style_transfer_plan.json"):
        for part in plan.parent.parts:
            if part.startswith("sty_") and "_cnt_" in part:
                out.add(part)
                break
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--content-dir", default="data/content")
    ap.add_argument("--style-dir", default="data/style")
    ap.add_argument("--contents", type=int, default=6)
    ap.add_argument("--styles", type=int, default=5)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--runs", default="result_rev_compare")
    ap.add_argument("--keep", default="compare/pairs.txt",
                    help="always include the pairs in this file, if their images exist")
    ap.add_argument("--out", default="compare/pairs_large.txt")
    args = ap.parse_args()

    cdir, sdir = ROOT / args.content_dir, ROOT / args.style_dir
    for d in (cdir, sdir):
        if not d.is_dir():
            raise SystemExit(f"not a directory: {d}")
    cs, ss = stems(cdir), stems(sdir)
    if not cs or not ss:
        raise SystemExit(f"no images: {len(cs)} content, {len(ss)} style")

    # Seed the grid with whatever the curated set already uses, so the existing
    # plans stay reusable and the figure cases remain in the counted set.
    keep_c, keep_s, keep_attr = [], [], {}
    kp = ROOT / args.keep
    if kp.exists():
        for line in kp.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                f = [x.strip() for x in line.split(",")]
                if len(f) > 2:
                    c, s = Path(f[1]).stem, Path(f[2]).stem
                    if c not in keep_c:
                        keep_c.append(c)
                    if s not in keep_s:
                        keep_s.append(s)
                    if len(f) > 3:
                        keep_attr[s] = f[3]

    rng = random.Random(args.seed)

    def extend(chosen, pool, n):
        avail = [p for p in pool if p.stem not in chosen]
        rng.shuffle(avail)
        picked = [p.stem for p in avail[: max(0, n - len(chosen))]]
        return chosen + picked

    sel_c = extend([c for c in keep_c if any(p.stem == c for p in cs)], cs, args.contents)
    sel_s = extend([s for s in keep_s if any(p.stem == s for p in ss)], ss, args.styles)
    if len(sel_c) < args.contents or len(sel_s) < args.styles:
        print(f"note: only {len(sel_c)} content and {len(sel_s)} style images available")

    cmap = {p.stem: p for p in cs}
    smap = {p.stem: p for p in ss}
    have = existing_plans(ROOT / args.runs)

    lines, reusable, new = [], [], []
    for s in sel_s:
        for c in sel_c:
            pid = f"sty_{s}_cnt_{c}"
            attr = keep_attr.get(s, "unannotated")
            mark = "reuses existing plan" if pid in have else "needs an agent run"
            lines.append(f"{pid},{cmap[c].relative_to(ROOT)},{smap[s].relative_to(ROOT)},{attr},{mark}")
            (reusable if pid in have else new).append(pid)

    out = ROOT / args.out
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        f"# {len(lines)} pairs = {len(sel_c)} contents x {len(sel_s)} styles, seed={args.seed}\n"
        f"# generated by scripts/make_pairs.py; {len(reusable)} reuse an existing plan,\n"
        f"# {len(new)} require an agent run before the plan can be replayed.\n"
        "# pair_id,content,style,style_attr,note\n" + "\n".join(lines) + "\n",
        encoding="utf-8")

    print(f"contents: {' '.join(sel_c)}")
    print(f"styles:   {' '.join(sel_s)}")
    print(f"\nwrote {out.relative_to(ROOT)}: {len(lines)} pairs "
          f"({len(reusable)} reusable, {len(new)} new)")
    if new:
        print(f"\nthe {len(new)} new pairs need plans first:")
        print(f"  python run_compare_batch.py --pairs {args.out} --final-dir outputs/ours")
    print(f"\nthen, for the plan-transfer table:")
    print(f"  python scripts/run_flux_local.py --pairs-file {args.out}")


if __name__ == "__main__":
    main()
